name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - '*/*/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
    - name: Get changed files
      id: getfile
      run: |
        # For pushes (including PR merges), get the previous commit on the master branch
        BASE=$(git rev-parse HEAD^1)
        FILES=$(git diff --name-only "$BASE" ${{ github.sha }} | xargs)
        echo "files=$FILES" >> $GITHUB_OUTPUT

    - name: Build, Tag, Publish Docker
      uses: ./.github/actions/build-image
      with:
        organization: rtibiocloud
        changed_files: ${{ steps.getfile.outputs.files }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
