name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - '*/*/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
    - name: Get changed files
      id: getfile
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE="${{ github.event.pull_request.base.sha }}"
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          # For pushes, get the previous commit on the branch
          PREVIOUS_COMMIT=$(git rev-parse HEAD^1) # Get the commit before the current one
          BASE=$PREVIOUS_COMMIT
        fi
        FILES=$(git diff --name-only "$BASE" ${{ github.sha }} | xargs)
        echo "files=$FILES >> $GITHUB_OUTPUT

    - name: Build, Tag, Publish Docker
      uses: ./.github/actions/build-image
      with:
        organization: rtibiocloud
        changed_files: ${{ steps.getfile.outputs.files }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
