name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - '*/*/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
    - name: get changed files
      id: getfile
      run: |
        echo "files=$(git diff --name-only ${{  github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
    - name: Build, Tag, Publish Docker
      uses: ./.github/actions/build-image
      with:
        organization: rtibiocloud
        changed_files: ${{ steps.getfile.outputs.files }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
